#!/usr/bin/env bash
# Install an autostart entry so the local-mask-mcp gateway comes up
# automatically whenever the user logs in.
#
# Chrome extensions cannot (by security design) start arbitrary
# processes on the host. The practical way to get a "gateway is
# always running" UX is to have the OS start the Docker container
# on login; once started, the container's ``restart: unless-stopped``
# policy keeps it alive across Docker daemon restarts.
#
# Strategy:
#   - Linux / WSL (systemd available): drop a user-level systemd
#     service that runs ``docker compose up -d`` from this repo.
#   - Linux / WSL (no systemd): fall back to a ``.bashrc`` / ``.profile``
#     hook that ``docker compose up -d``s on first shell login.
#   - Mac / other: print manual instructions and exit.
#
# Uninstall with ``scripts/install-autostart.sh --uninstall``.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SERVICE_NAME="mask-mcp-gateway"
UNIT_FILE="$HOME/.config/systemd/user/${SERVICE_NAME}.service"

usage() {
  cat <<EOF
usage: $0 [--uninstall]

Installs an autostart entry so '${SERVICE_NAME}' is brought up on
every login. Repository: $REPO_DIR

  --uninstall    Remove the systemd unit / profile hook.
  -h, --help     Show this message.
EOF
}

case "${1:-}" in
  -h|--help) usage; exit 0 ;;
esac

uninstall() {
  if [ -f "$UNIT_FILE" ]; then
    systemctl --user stop "$SERVICE_NAME" 2>/dev/null || true
    systemctl --user disable "$SERVICE_NAME" 2>/dev/null || true
    rm -f "$UNIT_FILE"
    systemctl --user daemon-reload 2>/dev/null || true
    echo "[autostart] removed systemd unit $UNIT_FILE"
  fi
  # Clean the bashrc marker if present.
  if [ -f "$HOME/.bashrc" ] && grep -q "# mask-mcp autostart" "$HOME/.bashrc"; then
    sed -i '/# mask-mcp autostart begin/,/# mask-mcp autostart end/d' "$HOME/.bashrc"
    echo "[autostart] removed .bashrc hook"
  fi
  echo "[autostart] done."
}

install_systemd() {
  mkdir -p "$(dirname "$UNIT_FILE")"
  cat > "$UNIT_FILE" <<UNIT
# Auto-generated by scripts/install-autostart.sh. Edit via that script.
[Unit]
Description=local-mask-mcp gateway
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
# RemainAfterExit makes ``systemctl status`` report the service as
# active even though the command exited — the real lifetime is
# managed by the container's own ``restart: unless-stopped`` policy.
RemainAfterExit=yes
WorkingDirectory=${REPO_DIR}
ExecStart=/usr/bin/env docker compose up -d
ExecStop=/usr/bin/env docker compose down
# Retry on failure so a transient ``docker daemon not ready yet``
# does not permanently disable autostart.
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
UNIT

  systemctl --user daemon-reload
  systemctl --user enable "$SERVICE_NAME"
  systemctl --user start "$SERVICE_NAME" || true

  echo "[autostart] systemd unit installed at $UNIT_FILE"
  echo "[autostart] service is enabled — it will start on every login."
  echo
  echo "  status : systemctl --user status $SERVICE_NAME"
  echo "  logs   : journalctl --user -u $SERVICE_NAME -f"
  echo "  stop   : systemctl --user stop $SERVICE_NAME"
  echo "  remove : $0 --uninstall"
}

install_bashrc() {
  local marker_begin="# mask-mcp autostart begin"
  local marker_end="# mask-mcp autostart end"
  if grep -q "$marker_begin" "$HOME/.bashrc" 2>/dev/null; then
    echo "[autostart] .bashrc hook already present; nothing to do."
    return
  fi
  cat >> "$HOME/.bashrc" <<HOOK

$marker_begin
# Start the mask-mcp gateway on first interactive login of this session.
# The ``restart: unless-stopped`` policy keeps it alive after that.
if [ -z "\${__MASK_MCP_AUTOSTARTED:-}" ] && [ -t 0 ]; then
  __MASK_MCP_AUTOSTARTED=1
  ( cd "${REPO_DIR}" && docker compose up -d >/dev/null 2>&1 & )
fi
$marker_end
HOOK
  echo "[autostart] .bashrc hook installed (systemd-user not available)."
  echo "[autostart] next interactive shell login will start the gateway."
}

# ---- main --------------------------------------------------------

if [ "${1:-}" = "--uninstall" ]; then
  uninstall
  exit 0
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "[autostart] ERROR: 'docker' not on PATH. Install Docker (Desktop on Windows/Mac) first." >&2
  exit 1
fi

# Decide strategy.
if command -v systemctl >/dev/null 2>&1 && systemctl --user --version >/dev/null 2>&1; then
  # Verify the user bus is actually reachable (WSL without
  # ``systemd=true`` in /etc/wsl.conf has systemctl but no active bus).
  if systemctl --user list-units >/dev/null 2>&1; then
    install_systemd
    exit 0
  fi
  echo "[autostart] systemd found but user bus unreachable." >&2
  if [ -n "${WSL_DISTRO_NAME:-}" ]; then
    echo "[autostart] WSL detected. Enable systemd with:" >&2
    echo "  sudo tee /etc/wsl.conf >/dev/null <<EOF" >&2
    echo "[boot]" >&2
    echo "systemd=true" >&2
    echo "EOF" >&2
    echo "  # then from PowerShell: wsl --shutdown, and reopen WSL." >&2
    echo >&2
  fi
  echo "[autostart] Falling back to ~/.bashrc hook instead." >&2
fi

install_bashrc
